### ISSUE TITLE
Wydać książkę liturgiczną [EPIC]

### ISSUE THREAD

**Issue by Jblew** [anielaolsztynek/poswiecenie-parafii-25lecie-ksiazki#1]
- [ ] - Nanieść poprawki językowe
- [ ] - Usunąć sieroty
- [ ] - Wstawić poprawioną okładkę
- [ ] - Wstawić zdjęcie Ołtarza do wewnętrznej strony przedniej okładki
- [ ] - Wstawić zdjęcie Ołtarza oddalone na tylną zewnętrzną okładkę
- [ ] - Wysłać finalną wersję do Księdza
- [ ] - Zadzwonić do Kraciuków (+48 602 351 818)
- [ ] - Wysłać Kraciukom wersję do druku
